<?php if ($this->pageCount): ?>
<span class="paginationControl">
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
      <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
        &lt; Vorheriges Projekt</a> |
    <?php endif; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
      <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
        Nächstes Projekt &gt;</a>
    <?php endif; ?>
</span>

<span class="activePage">Projekt <?php echo $this->current; ?> von <?php echo $this->pageCount; ?></span>
<?php endif; ?>