<p id="introtext">
	<span class="colortext">hello my friend</span>. wie schön, dass du hier bist.
	jd likes you macht <span class="colortext">grafik- und webdesign</span> aus berlin, 
	und es liegt mir am <span class="colortext">herzen</span>, dass dinge entstehen,
	die dich und mich <span class="colortext">begeistern.</span> design, das <span class="colortext">einfach</span> und 
	<span class="colortext">spannend</span> zugleich ist. viel spass und: <span class="colortext">i hope you like it, too.</span> 
</p>