
<p id="introtext">
	<span class="colortext">hello my friend</span>. schön, dass du hier bist.
	was jd likes you ist?
	<span class="colortext">grafik- und webdesign</span> aus berlin gebrandmarkt von 
 	<span class="colortext">kreativität</span>, <span class="colortext">schnelligkeit</span> und <span class="colortext">charakter</span>.
	zudem mag jd <span class="colortext">shortcuts</span> sehr.
	und das <span class="colortext">internet</span> sowieso.
	jd likes you macht <span class="colortext">schöne dinge</span> schöner.  
	just feel free to<span class="colortext"> contact me.</span> 
	<span class="colortext">♥</span>
</p>