<p id="introtext">
	<span class="colortext">Hello my friend.</span> Schön, dass du hier bist. 
	jd likes you ist <span class="colortext">Julia Dechert</span>, 
	Freelancerin für <span class="colortext">Grafik- und Webdesign</span> aus Berlin.
	jd macht mit PS, AI und ID <span class="colortext">Pixel und Papier</span> schön.
	
	So just <span class="colortext">contact me.</span>
	<span class="colortext">♥</span>
</p>




<!-- <p id="introtext">
	<span class="colortext">hello my friend</span>. schön, dass du hier bist.
	jd likes you macht <span class="colortext">grafik- und webdesign</span> aus berlin. 
	geprägt von <span class="colortext">kreativität</span>, <span class="colortext">schnelligkeit</span> 
	sowie <span class="colortext">charakter</span>.
	jd mag das<span class="colortext"> internet</span>.
	und macht <span class="colortext">schöne dinge</span> schöner.  
	just feel free to<span class="colortext"> contact me.</span> 
	<span class="colortext">♥</span>
</p>
-->

