<h2>Angaben gemäß § 5 TMG:</h2>
<p>
	Julia Dechert
	<br>
	Dolziger Straße 45
	<br>
	10247 Berlin
</p>

<h2>Kontakt:</h2>
<p>
	Email: <a href="mailto:hello@jdlikesyou.de">hello@jdlikesyou.de</a>
</p>

<h2>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:</h2>
<p>
	Julia Dechert
	<br>
	Dolziger Straße 45
	<br>
	10247 Berlin
	<br>
	Email: <a href="mailto:hello@jdlikesyou.de">hello@jdlikesyou.de</a>
</p>