<h2>Angaben gemäß § 5 TMG / 
	<br>
 	Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:</h2>
<p>
	Julia Dechert
	<br>
	Dolziger Straße 45
	<br>
	10247 Berlin
	<br>
	<br>
	Email: hello<span style="display: none">#NICHT TEIL DER EMAIL ADRESSE#</span>@<span style="display: none">#NICHT TEIL DER EMAIL ADRESSE#</span>jdlikesyou.de
</p>

<!-- <h2>Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:</h2>
<p>
	Julia Dechert
	<br>
	Dolziger Straße 45
	<br>
	10247 Berlin
	<br>
	Email: <a href="mailto:hello@jdlikesyou.de">hello@jdlikesyou.de</a>
</p>
-->