<p>
	Geboren in den Anfängen der 80er Jahre in Freiburg im Breisgau. </br>
	In Dornbirn (AT) am Bodensee das Bachelorstudium im Bereich Mediadesign absolviert. </br>
	Auslandssemster an der Akademie der Künste in Maastricht (NL). </br>
	Seit 2010 in Berlin.</p>

<h2>Relevante Berufserfahrung</h2>
Seit 2012: <span class="job-title">Selbstständige Grafik-&amp; Webdesignerin</span>
<p class="job-description">
	Umstrukturierung zur selbstständigen Grafik- und Webdesignerin
</p>

2011/12: <span class="job-title">Junior Art Director</span> Saint Elmo‘s Entertainment GmbH, Berlin
<p class="job-description">
	Verstärkter Einsatz auf Hauptkunden (INMS). </br>
	Konkretere gestalterische Maßnahmen: </br>
	Relaunch / Erweiterung des Webauftritts </br>
	Social Media Appearance </br>
	Umsetzungen von Kampagnen / Kampagnenerweiterungen für den Online-Bereich </br>
	</br>
	Weitere Kunden: </br>
	BMW, MSN … 	
</p>

2011: <span class="job-title">Trainee Art Director</span> Saint Elmo‘s Entertainment GmbH, Berlin
<p class="job-description">
	Als Trainee in einer Online-Agentur lernte ich schnell den Umgang mit Webdesign. Dabei wurde ich als unterstützende Designerin bei größeren Projekten eingesetzt sowie als gestalterische und konzeptionelle Kraft für kleinere Projekte, ebenso Pitches. 
	<br>
	Zu dem Kundenkreis gehörten u.a.: Initiative Neue Soziale Marktwirtschaft (INSM), BWM, MSN.  
</p>

2010/11: <span class="job-title">Praktikum Kommunikationsdesign</span> Doppelpunkt Kommunikationsdesign, Berlin<p class="job-description">
Im Praktikum bei Doppelpunkt gestaltete ich klassische Printmedien, wie bspw. Plakate, Postkarten und Broschüren. Dabei wurde ich voll in den Agenturprozess integriert und konnte den Aufgabenbereich der Printmedien erweitern. Jedoch auch weitere Bereiche, wie eine Logoanimationen und kurze Stopmotion-Filme, gehörten zu meinem Aufgabenbereich. 
</p>

2010: <span class="job-title">BA in Arts and Design</span> FH Vorarlberg, Dornbirn Österreich
<p class="job-description">
	Bachelorthesis zur Thematik "Staub". Dieses alltägliche Abfallprodukt wurde dabei als Gestaltungselement angesehen. Durch foto- und typografische Experimente entdeckte ich die Thematik und konnte sie transformiert widergegeben. Dem Betrachter werden neue Sichtweisen dargestellt. Ebenso liefert eine schlichte Textebene Informationen, lyrische Auffassungen oder weitere Beispiele zum Themengebiet. 
	<a href="http://issuu.com/juliadechert/docs/unermesslich____measureless"> Zur Bachelorarbeit</a> 	
</p>