<p>
	Julia Dechert, Grafik- und Webdesign in Berlin. </br>
	Geboren in den Anfängen der 80er Jahre in Freiburg im Breisgau. </br>
	In Dornbirn (AT) am Bodensee das Bachelorstudium im Bereich Mediadesign absolviert. </br>
	Auslandssemster an der Akademie der Künste in Maastricht (NL). </br>
	Seit 2010 in Berlin.</p>

<h2>Relevante Berufserfahrung</h2>
Seit 2012: <span class="job-title">Selbstständige Grafik-&amp; Webdesignerin</span>
<p class="job-description">
	Umstrukturierung zur selbstständigen Grafik- und Webdesignerin. </br>
	Bereichübergreifendes Denken und Zusammenarbeit. </br>
	Schnelle Abstimmungsphasen und naher Kundenkontakt verstärken den Prozess.
</p>

2011/12: <span class="job-title">Junior Art Director</span> Saint Elmo‘s Entertainment GmbH, Berlin
<p class="job-description">
	Verstärkter Einsatz auf den Hauptkunden Initiative Neue Soziale Marktwirtschaft (INSM). </br>
	Konkretere gestalterische Maßnahmen: </br>
	Relaunch / Erweiterung des Webauftritts </br>
	Social Media Appearance </br>
	Umsetzen von Kampagnen / Erweiterungen für den Online-Bereich </br>
	</br>
	Weitere Kunden: </br>
	u.a. BMW, MSN, DTM
</p>

2011: <span class="job-title">Trainee Art Director</span> Saint Elmo‘s Entertainment GmbH, Berlin
<p class="job-description">
	Gestaltung und Konzeption in Zusammenarbeit mit Senior ADs. </br>
	Eigene Projekte mit schneller Auffassungsgabe im Webdesign. </br>
	Zeitlich begrenzte Umsetzungen für Pitches. </br>
	<br>
	Kunden: Initiative Neue Soziale Marktwirtschaft (INSM), BWM, MSN.  
</p>

2010/11: <span class="job-title">Praktikum Kommunikationsdesign</span> Doppelpunkt Kommunikationsdesign, Berlin<p class="job-description">
	Gestaltung von klassischen Printmedien (u.a. Plakate, Postkarten und Broschüren) </br>
	Volle Integration in den Agenturprozess und starke Erweiterung im Umgang mit Printmedien. </br>
	Im Aufgabenbereich lag zudem die Gestaltungsvorgabe für Logoanimationen / Stopmotion-Filme.
</p>

2010: <span class="job-title">BA in Arts and Design</span> FH Vorarlberg, Dornbirn Österreich
<p class="job-description">
	Bachelorthesis zur Thematik "Staub". </br>
	Dabei wurde das alltägliche Abfallprodukt als Gestaltungselement angesehen. </br>
	Durch foto- und typografische Experimente wurde die Thematik transformiert widergegeben. </br>
	Dem Betrachter werden neue Sichtweisen dargestellt. </br>
	Schlichte Textebene liefern Informationen, lyrische Auffassungen oder weitere Beispiele zum Themengebiet. </br>
	<a href="http://issuu.com/juliadechert/docs/unermesslich____measureless"> Zur Bachelorarbeit</a> 	
</p>