<h1>Vita</h1>
<p>
	Julia Dechert wurde in den Anfängen der 80er Jahre im wunderschönen Freiburg im Breisgau geboren. Nach Abschluß der Schulkarriere und einem kurzzeitigen Aufenthalt in Stuttgart führten ihre Wege nach Österreich, genauer: nach Dornbirn, nahe am Bodensee. Dort das Bachelorstudium im Bereich Mediadesign absolviert, dazwischen ein Auslandssemster an der Akademie der Künste in Maastricht (NL), und der Weiterreise nach Berlin stand nichts mehr im Wege. Ja, und hier ist sie noch immer: in Berlin, der Stadt der 1000 Eindrücke und Inspirationen. Was sie so treibt oder getan hat? Steht hier drunter. 
</p>

<h2>Relevante Berufserfahrung</h2>
Seit 2012: <span class="job-title">Selbstständige Grafik-&amp; Webdesignerin</span>
<p class="job-description">
	Ich strukturierte mich um zur Selbstständigen. Dabei ist naher Kundenkontakt mit Abstimmungen und gemeinsamen Zielsetzungen eine wichtige Konstante in meinem Beruf. Online und Offline sind Thematiken, die breitgefächerte Designansätze mit sich bringen, sprich: das ständige Orientieren an den aktuellen Trends, neue Technologien auffassen und dabei auf die eindeutige Individualität acht geben. So sind kreative und zudem schnelle Ausarbeitungen möglich.
</p>

2011/12: <span class="job-title">Junior Art Director</span> Saint Elmo‘s Entertainment GmbH, Berlin
<p class="job-description">
	In der Position des Junior Art Directors wurde ich spezialisierter für einen Hauptkunden (INMS) eingesetzt. Meine gestalterischen Maßnahmen wurden hierfür konkretisiert, sodass ich Bereiche wie den Relaunch und die Erweiterung des Webauftritts, die Social Media Appearance, Umsetzungen von Kampagnen für den Online-Bereich und Kampagnenerweiterungen hierfür gestaltete.
</p>

2011: <span class="job-title">Trainee Art Director</span> Saint Elmo‘s Entertainment GmbH, Berlin
<p class="job-description">
	Als Trainee in einer Online-Agentur lernte ich schnell den Umgang mit Webdesign. Dabei wurde ich als unterstützende Designerin bei größeren Projekten eingesetzt sowie als gestalterische und konzeptionelle Kraft für kleinere Projekte, ebenso Pitches. 
	<br>
	Zu dem Kundenkreis gehörten u.a.: Initiative Neue Soziale Marktwirtschaft (INSM), BWM, MSN.  
</p>

2010/11: <span class="job-title">Praktikum Kommunikationsdesign</span> Doppelpunkt Kommunikationsdesign, Berlin<p class="job-description">
Im Praktikum bei Doppelpunkt gestaltete ich klassische Printmedien, wie bspw. Plakate, Postkarten und Broschüren. Dabei wurde ich voll in den Agenturprozess integriert und konnte den Aufgabenbereich der Printmedien erweitern. Jedoch auch weitere Bereiche, wie eine Logoanimationen und kurze Stopmotion-Filme, gehörten zu meinem Aufgabenbereich. 
</p>

2010: <span class="job-title">BA in Arts and Design</span> FH Vorarlberg, Dornbirn Österreich
<p class="job-description">
	Bachelorthesis zur Thematik "Staub". Dieses alltägliche Abfallprodukt wurde dabei als Gestaltungselement angesehen. Durch foto- und typografische Experimente entdeckte ich die Thematik und konnte sie transformiert widergegeben. Dem Betrachter werden neue Sichtweisen dargestellt. Ebenso liefert eine schlichte Textebene Informationen, lyrische Auffassungen oder weitere Beispiele zum Themengebiet. 
	<a href="http://issuu.com/juliadechert/docs/unermesslich____measureless"> Zur Bachelorarbeit</a> 	
</p>